### ISSUE TITLE
Error loading the key.pem cert. into the docker container 

### ISSUE THREAD

**Issue by MohamedSaidHamed** [angelo-v/docker-solid-server#1]
While running this image, it keeps bringing an exception about loading the key.pem certificate file. I tried to edit the docker-compose.yml "SOLID_SSL_KEY" from key.pem to privkey.pem "like certbot generated one" but it didn't work.

here is the exception stack 

`server_1_bcc3baf06840 | Generating a RSA private key
server_1_bcc3baf06840 | ..........................................................................................+++++
server_1_bcc3baf06840 | ........................................................................................................+++++
server_1_bcc3baf06840 | writing new private key to './solid-temporary.key'
server_1_bcc3baf06840 | -----
server_1_bcc3baf06840 | Finished: SUCCESS
server_1_bcc3baf06840 | TIP create a config.json: `$ solid init`
server_1_bcc3baf06840 | Thu, 11 Apr 2019 03:35:19 GMT solid:settings Server URI: https://mohamedsaidhamed.org
server_1_bcc3baf06840 | Thu, 11 Apr 2019 03:35:19 GMT solid:settings Auth method: oidc
server_1_bcc3baf06840 | Thu, 11 Apr 2019 03:35:19 GMT solid:settings Strict origins: true
server_1_bcc3baf06840 | Thu, 11 Apr 2019 03:35:19 GMT solid:settings Allowed origins:
server_1_bcc3baf06840 | Thu, 11 Apr 2019 03:35:19 GMT solid:settings Db path: ./.db
server_1_bcc3baf06840 | Thu, 11 Apr 2019 03:35:19 GMT solid:settings Config path: ./config
server_1_bcc3baf06840 | Thu, 11 Apr 2019 03:35:19 GMT solid:settings Suffix Acl: undefined
server_1_bcc3baf06840 | Thu, 11 Apr 2019 03:35:19 GMT solid:settings Suffix Meta: undefined
server_1_bcc3baf06840 | Thu, 11 Apr 2019 03:35:19 GMT solid:settings Filesystem Root: none
server_1_bcc3baf06840 | Thu, 11 Apr 2019 03:35:19 GMT solid:settings Allow WebID authentication: true
server_1_bcc3baf06840 | Thu, 11 Apr 2019 03:35:19 GMT solid:settings Live-updates: true
server_1_bcc3baf06840 | Thu, 11 Apr 2019 03:35:19 GMT solid:settings Multi-user: false
server_1_bcc3baf06840 | Thu, 11 Apr 2019 03:35:19 GMT solid:settings Suppress default data browser app: undefined
server_1_bcc3baf06840 | Thu, 11 Apr 2019 03:35:19 GMT solid:settings Default data browser app file path: default
server_1_bcc3baf06840 | Thu, 11 Apr 2019 03:35:19 GMT solid:settings Base URL (--mount): /
server_1_bcc3baf06840 | Thu, 11 Apr 2019 03:35:19 GMT solid:settings SSL Private Key path: /opt/solid/certs/key.pem
server_1_bcc3baf06840 | Thu, 11 Apr 2019 03:35:19 GMT solid:settings SSL Certificate path: /opt/solid/certs/fullchain.pem
server_1_bcc3baf06840 | ERROR Can't find SSL key in /opt/solid/certs/key.pem
server_1_bcc3baf06840 | Thu, 11 Apr 2019 03:35:19 GMT solid:authentication Provider keys loaded from config
server_1_bcc3baf06840 | Thu, 11 Apr 2019 03:35:19 GMT solid:authentication Provider keychain initialized
server_1_bcc3baf06840 | Thu, 11 Apr 2019 03:35:19 GMT solid:authentication Not sleeping before client registration...
server_1_bcc3baf06840 | Thu, 11 Apr 2019 03:35:19 GMT solid:authentication Client not present for issuer https://mohamedsaidhamed.org, initializing new client
server_1_bcc3baf06840 | Thu, 11 Apr 2019 03:35:19 GMT solid:authentication Registering new client for issuer  https://mohamedsaidhamed.org
server_1_bcc3baf06840 | Thu, 11 Apr 2019 03:35:19 GMT solid:authentication Error registering a new client:  { FetchError: request to https://mohamedsaidhamed.org/.well-known/openid-configuration failed, reason: read ECONNRESET
server_1_bcc3baf06840 |     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/solid-server/node_modules/node-fetch/lib/index.js:1444:11)
server_1_bcc3baf06840 |     at ClientRequest.emit (events.js:189:13)
server_1_bcc3baf06840 |     at TLSSocket.socketErrorListener (_http_client.js:392:9)
server_1_bcc3baf06840 |     at TLSSocket.emit (events.js:189:13)
server_1_bcc3baf06840 |     at emitErrorNT (internal/streams/destroy.js:82:8)
server_1_bcc3baf06840 |     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
server_1_bcc3baf06840 |     at process._tickCallback (internal/process/next_tick.js:63:19)
server_1_bcc3baf06840 |   message:
server_1_bcc3baf06840 |    'request to https://mohamedsaidhamed.org/.well-known/openid-configuration failed, reason: read ECONNRESET',
server_1_bcc3baf06840 |   type: 'system',
server_1_bcc3baf06840 |   errno: 'ECONNRESET',
server_1_bcc3baf06840 |   code: 'ECONNRESET' }
server_1_bcc3baf06840 | Thu, 11 Apr 2019 03:35:19 GMT solid:authentication Error initializing local RP client:  { FetchError: request to https://mohamedsaidhamed.org/.well-known/openid-configuration failed, reason: read ECONNRESET
server_1_bcc3baf06840 |     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/solid-server/node_modules/node-fetch/lib/index.js:1444:11)
server_1_bcc3baf06840 |     at ClientRequest.emit (events.js:189:13)
server_1_bcc3baf06840 |     at TLSSocket.socketErrorListener (_http_client.js:392:9)
server_1_bcc3baf06840 |     at TLSSocket.emit (events.js:189:13)
server_1_bcc3baf06840 |     at emitErrorNT (internal/streams/destroy.js:82:8)
server_1_bcc3baf06840 |     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
server_1_bcc3baf06840 |     at process._tickCallback (internal/process/next_tick.js:63:19)
server_1_bcc3baf06840 |   message:
server_1_bcc3baf06840 |    'request to https://mohamedsaidhamed.org/.well-known/openid-configuration failed, reason: read ECONNRESET',
server_1_bcc3baf06840 |   type: 'system',
server_1_bcc3baf06840 |   errno: 'ECONNRESET',
server_1_bcc3baf06840 |   code: 'ECONNRESET' }
`

**Comment by angelo-v** [comment]
Hi Mohamed, thanks for your report.

To be able to help you, I need some additional information:

- What operation system is your host running on?
- Are you mounting the certificate files from your host file system or another docker volume?
- Are the files accessible by UID 1000? (key.pem as SOLID_SSL_KEY and fullchain.pem as SOLID_SSL_CERT should be the correct ones)
- Do you have any security mechanism like SELinux running?

You could try executing into the container with `docker exec ...` or open a shell in a new container with `docker run -it --entrypoint sh ...` and try to read the files from perspective of the container.  Does this work?

**Comment by angelo-v** [comment]
The message comes from this code section in NSS, so something goes wrong accessing the file:

https://github.com/solid/node-solid-server/search?q=Can't+find+SSL+key+in&unscoped_q=Can't+find+SSL+key+in

Unfortunately the original error message is swallowed by NSS...

**Comment by MohamedSaidHamed** [comment]
- I'm running Ubuntu server 18.04
- I'm mounting them from my host file system
- Yes they are accessible by UID:1000 
- SELinux is disabled

**Comment by angelo-v** [comment]
Please run `openssl rsa -in key.pem -check` to check if your keyfile is ok. It should say "RSA key ok"  and print the private key.

Have you tried the `docker exec` command to see from perspective of the container?

**Comment by angelo-v** [comment]
The problem seams to be caused by only mounting the letsencrypt folder containing the symlinks, but not the actual cert / key files. https://superuser.com/questions/1357862/how-to-mount-certificates-from-certbot-to-use-inside-docker-container

**Comment by MohamedSaidHamed** [comment]
Thank to @angelo-v, The problem was resolved by loading the whole letsencrypt folder into the docker container and making sure that it has the right permissions.
