### ISSUE TITLE
Possibility to use a config.json file

### ISSUE THREAD

**Issue by bourgeoa** [angelo-v/docker-solid-server#3]
1. Will it be possible to use a **config.json file** as stated by the solid server documentation.
It is easy to reuse when building new version or a version with lots of params.

2. I cannot use your work on a **Synology NAS**. I suppose because the UID began at 1024 that's why I pushed my own **docker-hub** image at **bourgeoa/solid-server**

Anyway nice job.

**Comment by angelo-v** [comment]
1. You can mount a config.json file as a volume and do not provide env variables.
2. You can map host UID to container UIDs with the `-u` / `--user` option of docker run

Thanks :)
